// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxjbiquuwxygmehslzzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4amJpcXV1d3h5Z21laHNsenp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzY3NTEsImV4cCI6MjA2OTU1Mjc1MX0.SdttgP0Ucr0I4oa3azl_8SlE-xniMKUxYpKKaNq_uOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});